### ISSUE TITLE
Ionic.js

### ISSUE THREAD

**Issue by jigs1212** [rodrigo-fonseca/slide-tabs-ionic#1]
Do i need to change my ionic .js??
to make this work.

**Comment by rodrigo-fonseca** [comment]
Nops, you don't need do that.

**Comment by jigs1212** [comment]
I was not able to get it to work :(

**Comment by rodrigo-fonseca** [comment]
ok, but you've to be more specific about the problem

**Comment by jigs1212** [comment]
I am not able to see the contents of the tabs and swipe also not working .

I tried ti start new tabs project and coppied ur controllers and state and also the dashboard.html

**Comment by rodrigo-fonseca** [comment]
Did you tried to just clone the project? What type of error are you getting? What version of ionic are you using?

**Comment by rodrigo-fonseca** [comment]
I'm closing this issue

**Comment by jigs1212** [comment]
I am not able to swipe,
i am not getting any error,
i am using ionic 1.3.3

**Comment by rodrigo-fonseca** [comment]
I'm using this version without any problem, can you simulate this problem using codepen or any other? Show me your code

**Comment by jigs1212** [comment]
Will update u on this ASAP right now i moved on.
